version: ~> 1.0

sudo: true
dist: bionic

language: node_js
node_js:
  - 13
  - 12
  - 11

branches:
  only:
    - master
    - dev

cache: yarn

env:
  - NODE_ENV=testing DB_HOST=127.0.0.1 DB_PORT=27017 DB_NAME=crimemapdb_test DB_USER=crimemap DB_PASS=crimemappwd CODECOV_TOKEN=f9cb9c77-dcc3-447e-902e-8d997b65911c JWT_KEY=secret

install:
  - yarn install
  - yarn global add codecov
  - yarn global add nyc

services:
  - mongodb

before_script:
  - sleep 15
  - mongo crimemapdb_test --eval 'db.createUser({user:"crimemap",pwd:"crimemappwd",roles:[{role:"dbOwner", db:"crimemapdb_test"}]});'

script:
  - yarn lint
  - yarn test
  - codecov
