version: ~> 1.0

sudo: true
dist: bionic

language: node_js

branches:
  only:
    - master
    - dev

cache: yarn

env:
  - DB_HOST: '127.0.0.1'

services:
  - mongodb

before_script:
  - sleep 15
  - mongo crimemapdb --eval 'db.createUser({user:"crimemap",pwd:"crimemappwd",roles:[{role:"dbOwner", db:"crimemapdb"}]});'

jobs:
  include:
    - stage: lint
      node_js: '13'
      script:
        - yarn lint
    - stage: test
      node_js: '13'
      sudo: required
      script:
        - yarn test

stages:
  - lint
  - test
