version: "3.6"

services:
  database:
  api:
    image: crimemap-syn-api-dev
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: "development"
      DEBUG: "crimemap-sync-api"
    volumes:
      - ./:/app
