FROM node:13.3.0-alpine

ENV LC_ALL=en_US.UTF-8

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN apk add --update \
    python \
    python-dev \
    build-base \
  && rm -rf /var/cache/apk/*

RUN yarn install --production=true

COPY . .

CMD yarn start
