version: "3"

volumes:
  cm_dados_api:

networks:
  cm_network_api:
    driver: bridge

services:
  database:
    image: mongo:4.2
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
    networks:
      - cm_network_api
    expose:
      - "27017"
  api:
    build:
      context: ./
    container_name: api
    links: 
      - database
    depends_on:
      - database
    networks:
      - cm_network_api
    ports:
      - "4000:4000"
