version: '3.6'

volumes:
  cm_database_files:
  cm_database_config:

networks:
  cm_network_api:
    driver: bridge

services:
  database:
    image: mongo:4.2
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
      MONGO_INITDB_ROOT_PASSWORD: 'mongopwd'
    volumes:
      - cm_database_files:/data/db
      - cm_database_config:/data/configdb
      - ./scripts/mongo:/docker-entrypoint-initdb.d
    networks:
      - cm_network_api
    expose:
      - '27017'
  api:
    container_name: api
    environment:
      CORS_CLIENT_ORIGIN: '*'
      DB_HOST: 'database'
      DB_PORT: 27017
      DB_NAME: 'crimemapdb'
      DB_USER: 'crimemap'
      DB_PASS: 'crimemappwd'
      SYNC_API_ADMIN_USER: 'johndoe'
      SYNC_API_ADMIN_PASSWORD: 'abc'
    links:
      - database
    depends_on:
      - database
    networks:
      - cm_network_api
    ports:
      - '4000:4000'
