version: '3.6'

volumes:
  database_files:
  database_config:

networks:
  network_api:
    driver: bridge

services:
  database:
    image: mongo:4.2
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
      MONGO_INITDB_ROOT_PASSWORD: 'mongopwd'
    volumes:
      - database_files:/data/db
      - database_config:/data/configdb
      - ./init.db.sh:/docker-entrypoint-initdb.d/init.db.sh
    networks:
      - network_api
    expose:
      - '27017'
    ports:
      - '27017:27017'
  api:
    image: prsales/crimemap-sync-api
    container_name: api
    environment:
      NODE_ENV: 'development'
      DEBUG: 'crimemap-sync-api'
      CORS_CLIENT_ORIGIN: '*'
      DB_HOST: 'database'
      DB_PORT: 27017
      DB_NAME: 'crimemapdb'
      DB_USER: 'crimemap'
      DB_PASS: 'crimemappwd'
      SYNC_API_ADMIN_USER: 'johndoe'
      SYNC_API_ADMIN_PASSWORD: 'abc'
    links:
      - database
    depends_on:
      - database
    networks:
      - network_api
    ports:
      - '4000:4000'
